cloud/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.home, name='home-page'),
    path('register/', views.register, name='register'),
    path('profile/', views.profile, name='profile'),
    path('groups/', views.groups, name='groups'),
    path('group/<int:pk>', views.GroupDetailView.as_view(), name='group-detail'),
    path('user/<int:pk>', views.UserDetailView.as_view(), name='user-detail'),
    path('file/<int:pk>', views.FileDetailView.as_view(), name='file-detail'),
    path('folders/', views.file, name='folders'),
    path('folder/new/', views.FolderCreateView.as_view(), name='folder-create'),
    path('folder/<int:pk>/update/', views.FolderUpdateView.as_view(), name='folder-update'),
    path('folder/<int:pk>/delete/', views.FolderDeleteView.as_view(), name='folder-delete'),
    path('contacts/', views.contacts, name='contacts'),
    path('contacts/<int:pk>', views.ContactDetailView.as_view(), name='contract-detail'),
    path('folder/<int:pk>', views.FolderDetailView.as_view(), name='folder-detail'),
    path('share/<int:pk>', views.SharedFileDetailView.as_view(), name='share-detail'),
    path('file/new/', views.FileCreateView.as_view(), name='file-create'),
    path('file/move/', views.FileFolderCreate.as_view(), name='file-folder-create'),
    path('file/<int:pk>/update/', views.FileUpdateView.as_view(), name='file-update'),
    path('file/<int:pk>/delete/', views.FileDeleteView.as_view(), name='file-delete'),
    path('contactCreate/', views.ContactCreateView.as_view(), name='contactCreate'),
    path('contacts/<int:pk>/delete/', views.ContactDeleteView.as_view(), name='contact-delete'),
    path('share/', views.ShareCreateView.as_view(), name='share-user'),
    path('groupCreate/', views.GroupCreateView.as_view(), name='group-create'),
    path('groupFill/', views.FillGroupView.as_view(), name='group-fill'),

]

"""urlpatterns = [
    path('', views.home, name='home-page'),
    path('register/', views.register, name='register'),
    path('profile/', views.profile, name='profile'),
    path('folders/', views.file, name='folders'),
    path('folder/<int:pk>/', views.FolderDetailView.as_view(), name='folder-detail'),
    path('folder/new/', views.FolderCreateView.as_view(), name='folder-create'),
    path('folder/<int:pk>/update/', views.FolderUpdateView.as_view(), name='folder-update'),
    path('folder/<int:pk>/delete/', views.FolderDeleteView.as_view(), name='folder-delete'),
    path('folder/<int:pk1>/file/<int:pk2>/', views.FileDetailView.as_view(), name='file-detail'),
]"""

cloud_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
#from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('register/', views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='cloud/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='cloud/logout.html'), name='logout'),

    path('', include('cloud.urls')),
    path('', include('cloud.urls')),
    path('', include('cloud.urls')),
   # path('', include('cloud.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cloud/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.contrib.auth.models import Group
from django.urls import reverse
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.


class tbl_user(models.Model):
    #on = models.ForeignKey('tbl_folder', on_delete=models.SET_NULL, null=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    #bio = models.TextField(max_length=500, blank=True)
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')
    location = models.CharField(max_length=30, blank=True)
    birth_date = models.DateField(null=True, blank=True)
    phone_number = models.CharField(max_length=12, blank=True)
    language = models.CharField(max_length=30, blank=True)

    def __str__(self):
        return f'{self.user.username} Profile'

    def get_absolute_url(self):
        """Returns the url to access a detail record for this book."""
        return reverse('user-detail', args=[str(self.user.pk)])

    """def save(self):
        super().save()

        img = Image.open(self.image.path)

        if img.height > 300  or img.width > 300:
            output_size = (300,300)
            img.thumbnail(output_size)
            img.save()"""


class tbl_groups(models.Model):
    group_id = models.AutoField(primary_key=True)
    isAdmin = models.BooleanField(default=False)
    group_name = models.CharField(max_length=50, blank=False)

    def get_absolute_url(self):
        """Returns the url to access a detail record for this book."""
        return reverse('group-detail', args=[str(self.group_id)])

    def __str__(self):
        return self.group_name
class tbl_groups_user(models.Model):
    group_id = models.ForeignKey(tbl_groups, on_delete=models.CASCADE, blank=False)
    user_id = models.ForeignKey(tbl_user, on_delete=models.CASCADE, blank=False)
    def get_absolute_url(self):
        """Returns the url to access a detail record for this book."""
        return reverse('group-detail', args=[str(self.group_id)])

class tbl_file(models.Model):
    file_id = models.AutoField(primary_key=True)
    owner_id = models.ForeignKey(tbl_user, on_delete=models.CASCADE)
    size = models.IntegerField()
    date = models.DateTimeField(default=timezone.now)
    title = models.CharField(max_length=200)
    isFav = models.BooleanField(default=False)

    """def get_absolute_url(self):
        return reverse('file-detail', args=[str(self.file_id)])"""
    def get_absolute_url(self):
        return reverse('file-detail', kwargs={'pk':self.file_id})

    def __str__(self):
        return self.title

class tbl_image(tbl_file):
    resolution = models.IntegerField()
    def __str__(self):
        return self.title
        
class tbl_music(tbl_file):
    time = models.IntegerField()
    artist = models.CharField(max_length=50)
    mType = models.CharField(max_length=50)
    album = models.CharField(max_length=50)

    
    def __str__(self):
        return self.title

class tbl_video(tbl_file):
    vType = models.CharField(max_length=50)
    resolution = models.IntegerField()
    time = models.IntegerField()

    
    def __str__(self):
        return self.title

class tbl_folder(models.Model):
    folder_id = models.AutoField(primary_key=True)
    owner_id = models.ForeignKey(tbl_user, on_delete=models.CASCADE, verbose_name='Owner')
    parent_folder = models.ForeignKey('self', on_delete=models.CASCADE, blank=True, null=True, related_name='tbl_folder')
    size = models.IntegerField()
    date = models.DateTimeField(default=timezone.now)
    title = models.CharField(max_length=200)
    describtion = models.CharField(max_length=200)
    isFav = models.BooleanField(default=False)

    def get_all_children(self,include_self=True):
        r=[]
        if include_self:
            r.append(self)
        for c in tbl_folder.objects.filter(parent_folder=self):
            _r = c.get_all_children(include_self=True)
            if 0<len(_r):
                r.extend(_r)
        return r
    def __str__(self):
        return self.title
    #def get_absolute_url(self):
     #   return reverse('folder-detail', args=[str(self.folder_id)])
    
    def get_absolute_url(self):
        return reverse('folder-detail', kwargs={'pk':self.pk})




class tbl_folder_file(models.Model):
    folder_id = models.ForeignKey(tbl_folder, on_delete=models.CASCADE, blank=True)
    file_id = models.ForeignKey(tbl_file, on_delete=models.CASCADE, blank=True)
    def get_absolute_url(self):
        return reverse('folder-detail', kwargs={'pk':self.pk})

class tbl_address(models.Model):
	owner_id = models.ForeignKey(tbl_user, on_delete=models.CASCADE)
	adType = models.CharField(max_length=50)
	extAddress = models.CharField(max_length=500)
	post_code = models.IntegerField()
	city = models.CharField(max_length=100)
	country = models.CharField(max_length=100)

	def __str__(self):
		return self.adType

class tbl_social_media(models.Model):
    owner_id = models.ForeignKey(tbl_user, on_delete=models.CASCADE, blank=False, verbose_name='Owner')
    media_type = models.CharField(max_length=50)
    def __str__(self):
        return self.media_type

class tbl_contact(models.Model):
    contact_id = models.AutoField(primary_key=True)
    owner_id = models.ForeignKey(tbl_user, on_delete=models.CASCADE, blank=False, verbose_name='Contact User:')
    full_name = models.CharField(max_length=50)
    e_mail = models.EmailField(max_length=50)
    phone_number = models.CharField(max_length=12, blank=True, help_text='Please fill with a maximum 12-digit phone number')
    location = models.CharField(max_length=30, blank=True)
    from_next_cloud_or_another = models.BooleanField(default=False)

    def __str__(self):
        return self.full_name
    def get_absolute_url(self):
        """Returns the url to access a detail record for this book."""
        return reverse('contract-detail', args=[str(self.contact_id)])

class tbl_share_with_user(models.Model):
    share_id = models.AutoField(primary_key=True)
    file_id = models.ForeignKey(tbl_file, on_delete=models.CASCADE, blank=False, verbose_name='File Name')
    user_id = models.ForeignKey(tbl_user, on_delete=models.CASCADE, blank=False, verbose_name='User Name', related_name='+')#, related_name='+'
    user_id2 = models.ForeignKey(tbl_user, on_delete=models.CASCADE, blank=False, verbose_name='Shared User')
    expire_on = models.DateField(default=timezone.now)
    readable_writable = models.BooleanField(default=False)
    def get_absolute_url(self):
        """Returns the url to access a detail record for this book."""
        return reverse('share-detail', args=[str(self.share_id)])

class tbl_external_user(models.Model):
    uuid = models.AutoField(primary_key=True)
    user_name = models.CharField(max_length=50)
    e_mail = models.EmailField(max_length=50)
    def __str__(self):
        return self.user_name

class tbl_share_external(models.Model):
    share_id = models.AutoField(primary_key=True)
    file_id = models.ForeignKey(tbl_file, on_delete=models.CASCADE, blank=False, verbose_name='File Name')
    user_id = models.ForeignKey(tbl_external_user, on_delete=models.CASCADE, blank=False, verbose_name='User Name')
    expire_on = models.DateField(default=timezone.now)

cloud/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm
from django.views import generic
from django.views.generic import CreateView, UpdateView, DeleteView
from django.db.models import Count
from .models import (tbl_user, tbl_file, tbl_image,
	tbl_music,
	tbl_video,
	tbl_folder,
	tbl_folder_file,
	tbl_address,tbl_contact,tbl_groups,
	User,
	tbl_share_with_user,
	tbl_groups_user)



@login_required
def home(request):

	num_groups = tbl_groups.objects.all().count()
	num_files = tbl_file.objects.all().count()

	# Available books (status = 'a')
	num_folder = tbl_folder_file.objects.count()

	# The 'all()' is implied by default.
	num_shared = tbl_share_with_user.objects.count()
	# Number of visits to this view, as counted in the session variable.
	num_visits = request.session.get('num_visits', 0)
	request.session['num_visits'] = num_visits + 1

	context = {
		'num_groups': num_groups,
		'num_files': num_files,
		'num_folder': num_folder,
		'num_shared': num_shared,
		'num_visits': num_visits,
	}

	"""context ={
		'folders':tbl_folder.objects.all()

	}"""
	return render(request, 'cloud/home.html', context)

def register(request):
	if request.method =='POST':
		form = UserRegisterForm(request.POST)
		if form.is_valid():
			form.save()
			username = form.cleaned_data.get('username')
			messages.success(request, f'Your account has been created! You are now able to log in')
			return redirect('login')
	else:
		form = UserRegisterForm()
	return render(request, 'cloud/register.html', {'form':form})

@login_required
def profile(request):
	if request.method == 'POST':
		u_form = UserUpdateForm(request.POST, instance = request.user)
		p_form = ProfileUpdateForm(request.POST, request.FILES, instance = request.user.tbl_user)

		if u_form.is_valid() and p_form.is_valid():
			u_form.save()
			p_form.save()
			messages.success(request, f'Your account has been updated!')
			return redirect('profile')

	else:
		u_form = UserUpdateForm(instance = request.user)
		p_form = ProfileUpdateForm(instance = request.user.tbl_user)
	context = {
		'u_form' : u_form,
		'p_form' : p_form
	}
	return render(request, 'cloud/profile.html', context) 

def file(request):
	context= {
		'folders': tbl_folder.objects.all(),
		'files':tbl_file.objects.all()
	}
	return render(request, 'cloud/tbl_folder_list.html', context)

def contacts(request):
	context = {
		'contacts':tbl_contact.objects.all(),
	}
	return render(request,'cloud/tbl_contact_list.html',context)
def groups(request):
	context={
		'groups':tbl_groups.objects.all()
	}
	return render(request,'cloud/tbl_groups_list.html',context)


class FileDetailView(generic.DetailView):
	model = tbl_file
	"""def get_object(self):
	        pk1 = self.kwargs['pk1']
	        pk2 = self.kwargs['pk2']
	        folder = get_object_or_404(tbl_folder, pk=pk1)
	        file = get_object_or_404(tbl_file, pk=pk2)
	        return file"""

class ContactDetailView(generic.DetailView):
	model = tbl_contact
class GroupDetailView(generic.DetailView):
	model = tbl_groups
class GroupUserDetailView(generic.DetailView):
	model = tbl_groups_user
class UserDetailView(generic.DetailView):
	model = User
class SharedFileDetailView(generic.DetailView):
	model = tbl_share_with_user

class FolderDetailView(generic.DetailView):
	model = tbl_folder

class FolderListView(generic.ListView):
    model = tbl_folder

class FolderCreateView(LoginRequiredMixin, CreateView):
	model = tbl_folder
	fields = ['parent_folder' ,'title', 'describtion', 'size', 'isFav']

	def form_valid(self, form):
		#form.instance.Owner = self.request.user
		form.instance.owner_id = self.request.user.tbl_user
		return super().form_valid(form)

class FolderUpdateView(LoginRequiredMixin, UpdateView):
	model = tbl_folder
	fields = ['parent_folder' ,'title', 'describtion', 'size', 'isFav']
	success_url='/'

	def form_valid(self, form):
		#form.instance.Owner = self.request.user
		form.instance.owner_id = self.request.user.tbl_user
		return super().form_valid(form)

	"""def test_func(self): # cok gerekli olmaya bir sey
		folder = self.get_object()
		if self.request.user.tbl_user == folder.owner_id: 
			return True
		return False"""

class FolderDeleteView(LoginRequiredMixin, DeleteView):
    model = tbl_folder
    success_url ='/'
    """def test_func(self): # cok gerekli olmaya bir sey
		folder = self.get_object()
		if self.request.user.tbl_user == folder.owner_id: 
			return True
		return False"""
class FileCreateView(CreateView):
	model = tbl_file
	fields =['title','isFav','size']
	#success_url='file/new/new/'
	def form_valid(self, form):
		#form.instance.Owner = self.request.user
		form.instance.owner_id = self.request.user.tbl_user
		return super().form_valid(form)

class FileFolderCreate(CreateView):
	model = tbl_folder_file
	fields = ['folder_id','file_id']
	success_url = '/'

	def form_valid(self, form):
		#form.instance.Owner = self.request.user
		form.instance.owner_id = self.request.user.tbl_user
		return super().form_valid(form)

class FileUpdateView(LoginRequiredMixin, UpdateView):
	model = tbl_file
	fields = ['title','isFav','size']
	#success_url='/'

	def form_valid(self, form):
		#form.instance.Owner = self.request.user
		form.instance.owner_id = self.request.user.tbl_user
		return super().form_valid(form)

class FileDeleteView(LoginRequiredMixin, DeleteView):
    model = tbl_file
    success_url ='/'

class ContactCreateView(CreateView):
	model = tbl_contact
	fields =['owner_id','full_name','e_mail','phone_number','location','from_next_cloud_or_another']

	def form_valid(self, form):
		#form.instance.Owner = self.request.user
		form.instance.owner_id = self.request.user.tbl_user
		return super().form_valid(form)

class ContactDeleteView(DeleteView):
	model = tbl_contact
	success_url ='/'

class ShareCreateView(CreateView):
	model = tbl_share_with_user
	fields = ['file_id', 'user_id', 'user_id2', 'expire_on', 'readable_writable']
	def form_valid(self, form):
		#form.instance.Owner = self.request.user
		form.instance.owner_id = self.request.user.tbl_user
		return super().form_valid(form)

class GroupCreateView(CreateView):
	model = tbl_groups
	fields = ['group_name', 'isAdmin']

	def form_valid(self, form):
		#form.instance.Owner = self.request.user
		form.instance.owner_id = self.request.user.tbl_user
		return super().form_valid(form)

class FillGroupView(CreateView):
	model = tbl_groups_user
	fields = ['group_id', 'user_id'] 
	success_url = '/'
	def form_valid(self, form):
		#form.instance.Owner = self.request.user
		form.instance.owner_id = self.request.user.tbl_user
		return super().form_valid(form)

cloud/templates/cloud/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'cloud/main.css' %}">

    {% if title %}
        <title>Django Blog - {{ title }}</title>
    {% else %}
        <title>Django Blog</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="{% url 'home-page' %}">Django Cloud</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{% url 'home-page' %}">Home</a>
              <a class="nav-item nav-link" href="#">Calendar</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
            	{% if user.is_authenticated %}
                <a class="nav-item nav-link" href="{% url 'contactCreate' %}">New Contact</a>
            		<a class="nav-item nav-link" href="{% url 'profile' %}">Profile</a>
                <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
            	{% else %}
	              <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
	              <a class="nav-item nav-link" href="{% url 'register' %}">Register</a>
	            {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
        	{% if messages %}
        		{% for message in messages %}
        			<div class="alert alert-{{ message.tags }}">
        				{{ message }}
        			</div>
        		{% endfor %}
        	{% endif %}
          {% block content %}{% endblock %}
        	
        </div>
        <div class="col-md-4">
          <div class="content-section">
            {% if user.is_authenticated %}
              <h3>New Folder/File</h3>
              <p class='text-muted'>You can upload a folder or file here.
                <ul class="list-group">
                  <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'folder-create' %}">Upload New Folder</a>
                  <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'file-create' %}">Upload New File</a>
                  {% block content2 %}{% endblock %}
                </ul>
              </p>
            {% else %}
              <h3>Welcome to our Django Cloud System</h3>
              <p class='text-muted'>You can upload a folder or file here. Or share files with your friends. Do not have an account? 
              
              </p>
            {% endif %}
          </div>
          {% if user.is_authenticated %}
            <div class="content-section">
              
                <h3>Share</h3>
                <p class='text-muted'>You can share a file here.
                  <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'share-user' %}">Share</a>
                </p>
              
            </div>
            <div class="content-section">
              
                <h3>Move File</h3>
                <p class='text-muted'>You can move a file from another folder.
                  <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'file-folder-create'%}">Move File</a>
                </p>
              
            </div>
          {% endif %}
        </div>

        

      </div>
    </main>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

cloud/templates/cloud/home.html
{% extends "cloud/base.html" %}
{% block content %}
    
    {% if user.is_authenticated %}

        

        <h1 style="color:blue;">Home Page</h1>

        

        <h2>  Cloud System</h2>
        <p>Welcome to Cloud System, a website developed by <em>Tugay Calyan and Furkan Gurel</em>!</p>
        <h3>Dynamic content</h3>
        <p>The Cloud System has the following record counts:</p>
        <ul>
            <li><strong>Number of Groups:</strong> {{ num_groups }}</li>
            <li><strong>Number of Files:</strong> {{ num_files }}</li>
            <li><strong>Number of Folder:</strong> {{ num_folder }}</li>
            <li><strong>Number of Shared Files:</strong> {{ num_shared }}</li>
        </ul>
        <p>You have visited this page {{ num_visits }}{% if num_visits == 1 %} time{% else %} times{% endif %}.</p>
        <article class="media content-section">
            <div class="media-body">
                <div class="article-metadata">
                    <a class="mr-2" href="{% url 'folders' %}">Folders,Files and Shared Files</a>

                </div>
                <div class="article-metadata">
                    <a class="mr-2" href="{% url 'contacts' %}">Contacts</a>
                </div>
                <div class="article-metadata">
                    <a class="mr-2" href="{% url 'groups' %}">Groups</a>
                </div>

            </div>
        </article>
    {% endif %}
{% endblock content %}

cloud/templates/cloud/profile.html
{% extends "cloud/base.html" %}
{% load crispy_forms_tags %}
{% block content %}

	<div class="content-section">
	  <div class="media">
	    <img class="rounded-circle account-img" src="{{ user.tbl_user.image.url }}">
	    <div class="media-body">
	      <h2 class="account-heading">{{ user.username }}</h2>
	      <p class="text-secondary">{{ user.email }}</p>
	    </div>
	  </div>
	  <!-- FORM HERE -->
	  <form method="POST" enctype="multipart/form-data">
			{% csrf_token %}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">Profile Info</legend>
				{{ u_form|crispy }}
				{{ p_form|crispy }}
			</fieldset>
			<div class="form-group">
				<button class="btn btn-outline-info" type="submit">Update</button>
			</div>

		</form>
	</div>

{% endblock content %}

cloud/templates/cloud/register.html
{% extends "cloud/base.html" %}
{% load crispy_forms_tags %}
{% block content %}

	<div class="content-section">
		<form method="POST">
			{% csrf_token %}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">Join Us</legend>
				{{ form|crispy }}
			</fieldset>
			<div class="form-group">
				<button class="btn btn-outline-info" type="submit">Sign Up</button>
			</div>

		</form>
		<div class="border-top pt-3">
			<small class="text-muted">
				Already Have An Account? <a class="ml-2" href="{% url 'login' %}">Sign In</a>
			</small>

		</div>

	</div>
{% endblock content %}

cloud/templates/cloud/tbl_contact_list.html
{% extends "cloud/base.html" %}
{% block content %}
    {% if user.is_authenticated %}
        {% for contact in contacts %}
            {% if contact.owner_id.user.username == user.username %}
                <article class="media content-section">
                    <div class="media-body">
                        <div class="article-metadata">
                            <a class="mr-2" href="{{ contact.get_absolute_url }}">{{ contact.full_name }}</a>
                            <small class="text-muted">{{ contact.e_mail }}</small>
                        </div>
                    </div>
                </article>
            {% endif %}
        {% endfor %}
    {% endif %}
{% endblock content %}

cloud/templates/cloud/tbl_file_confirm_delete.html
{% extends "cloud/base.html" %}
{% block content %}

	<div class="content-section">
		<form method="POST">
			{% csrf_token %}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">Delete Folder</legend>
				<h2>Are you sure you want to delete the folder "{{ object.title }}"</h2>
			</fieldset>
			<div class="form-group">
				<button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
				<a class="btn btn-outline-secondary" href="{% url 'home-page' %}">Cancel</a>
			</div>

		</form>

	</div>
{% endblock content %}

cloud/templates/cloud/tbl_groups_detail.html
{% extends "cloud/base.html" %}
{% block content %}

    {% if user.is_authenticated %}
                {% for group_user in tbl_groups.tbl_groups_user_set.all%}
                    {% if group_user.user_id.user.username != user.username%}
                        <article class="media content-section">
                            <div class="media-body">
                                <div class="article-metadata">
                                    <a class="mr-2" href="{{ group_user.user_id.get_absolute_url }}">{{ group_user.user_id.user.username }}</a>
                                </div>
                            </div>
                        </article>
                    {% endif %}
                {% endfor %}
    {% endif %}
{% endblock content %}

cloud/templates/cloud/tbl_groups_list.html
{% extends "cloud/base.html" %}
{% block content %}

    {% if user.is_authenticated %}
        {% for group in groups %}
                {% for group_user in group.tbl_groups_user_set.all %}
                    {% if group_user.user_id.user.username == user.username%}
                        <article class="media content-section">
                            <div class="media-body">
                                <div class="article-metadata">
                                    <a class="mr-2" href="{{ group.get_absolute_url }}">{{ group.group_name }}</a>
                                </div>
                            </div>
                        </article>
                    {% endif %}
                {% endfor %}
        {% endfor %}
    {% endif %}
{% endblock content %}